name: Static Pages Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'fronted/**'   # 监控文件夹及其子文件夹内的所有文件
      - '.github/workflows/static_pages_build.yml' 
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-fronted:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # 设置 Node.js 版本（可以根据项目要求调整）


      - name: Install dependencies
        run: npm install
        working-directory: ./frontend  # 设置工作目录为 frontend 文件夹

      - name: Build React app
        run: npm run build
        working-directory: ./frontend  # 设置工作目录为 frontend 文件夹

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: "./frontend/dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    